version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    environment:
      - MQTT_USER=${MQTT_USER:-monitoring}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-monitoring123}
    networks:
      - monitoring-network

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-MonitoreoDB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./CreateTables.sql:/docker-entrypoint-initdb.d/CreateTables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - monitoring-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - DB_NAME=${POSTGRES_DB:-MonitoreoDB}
      - MQTT_BROKER=mqtt-broker
      - MQTT_PORT=1883
      - MQTT_USER=${MQTT_USER:-monitoring}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-monitoring123}
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
    depends_on:
      postgres:
        condition: service_healthy
      mqtt-broker:
        condition: service_started
    networks:
      - monitoring-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin123}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - monitoring-network

  simulador:
    build:
      context: ./simulador
      dockerfile: Dockerfile
    environment:
      - MQTT_BROKER=mqtt-broker
      - MQTT_PORT=1883
      - MQTT_USER=${MQTT_USER:-monitoring}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-monitoring123}
      - SEND_INTERVAL=5000
    depends_on:
      - mqtt-broker
    networks:
      - monitoring-network

  fog-node:
    build:
      context: ./fog-node
      dockerfile: Dockerfile
    environment:
      - DB_HOST=${POSTGRES_HOST:-postgres}
      - DB_USER=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - DB_NAME=${POSTGRES_DB:-MonitoreoDB}
      - MQTT_BROKER=tcp://mqtt-broker:1883
      - MQTT_PORT=1883
      - MQTT_USER=${MQTT_USER:-monitoring}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-monitoring123}
    depends_on:
      - mqtt-broker
      - postgres
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge

volumes:
  postgres_data:
  grafana_data: 