apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: ${POSTGRES_USER:-postgres}
    secureJsonData:
      password: ${POSTGRES_PASSWORD:-postgres}
    jsonData:
      database: ${POSTGRES_DB:-MonitoreoDB}
      sslmode: disable
    editable: true
    isDefault: true 